require("josh.options")
require("josh.keymaps")
require("josh.plugins")
require("josh.colorscheme")
require("josh.cmp")
require("josh.lsp")
require("josh.telescope")
require("josh.treesitter")
require("josh.autocmd")
require("josh.trouble")
require("josh.spectre")
require("josh.diffview")

require("colorizer").setup()
