# Project Proposal

I'd like to make some kind of head-wear (let's call it a hat) which covers the eyes and muffles the hearing (ear defenders) and provides different forms of sensory feedback. A key feature would be the use of small vibration motors (found in mobile phones) placed around to the hat which will provide some haptic feed back of the environment around the wearer. I also want to play with vision in a different way, by placing lights (probably LEDs, ideally filament bulbs but this seems more dangerous) which can pulse or flash, but to closed eyes, providing only the sensation of brightness. Finally I plan on putting small speakers in the ear defenders which again could provide some abstraction of the environment being navigated, and perhaps adding to disorientation.

The hat will receive feedback through sonar proximity sensors, phototransistors/LDRs (or something with more sensitivity), possibly a microphone. I would love for the system to be wireless too, so there would have to be an internal power source.

It would need 'housing' in a number of ways. There would need to be a fabric element to the head-wear, which I would probably sew something bespoke. I imagine there would be lots of smaller individual cases for separate elements and circuits in the system, which I would most likely 3D prints and sew in/on to the fabric. I would be drawing visual inspiration from Sci-Fi helmets and space exploration head-wear.

With all this in place, there are many different avenues I would like to explore with are largely dependant on the rate the project progresses. The system could solely react to the real environment the wearer is in, and augment this experience, which could lead to some interesting ways in which the wearer must navigate and understand the environment. It could also act like an Occulus Rift, where the wearer is actually in a virtual space and must navigate based purely on the feedback they are getting around their head. This could lend itself to an interesting game, perhaps puzzles or mazes which need to be solved without any visual feedback. It could also react to some kind of invisible stimuli, perhaps Bluetooth or WiFi signals in the room, or magnetic compass directions which could be incorporated with a Magnetometer board.

This is all in response to different elements of what I have been reading over the last few weeks. I want a system which has drastically unusual means of feedback and response. Creating a menu or selection system, or even just 'start' and 'game over' style stimuli with this system would be an interesting challenge. I also like the idea of exploring hidden or invisible environments particularly when very human senses are taken away. There is scope for it to change, the vibration motors are an early idea, but in an ideal world I would love for the feedback to be stranger.
